#!/bin/bash
temp_photo_dir=~/Pictures/temp

mogrify -resize 968x648 ~/Pictures/temp*.jpg
montage ~/Pictures/temp*.jpg -tile 2x2 -geometry +10+10 /home/pi/temp_montage2.jpg
montage /home/pi/temp_montage2.jpg /home/pi/photobooth_label.jpg -tile 2x1 -geometry +5+5 /home/pi/temp_montage3.jpg
lp /home/pi/temp_montage3.jpg
suffix=$(date +%H%M%S)
cp /home/pi/temp_montage3.jpg /home/pi/PB_archive/PB_${suffix}.jpg
rm ~/Pictures/temp*.jpg
rm /home/pi/temp*
